version: '3'
services:
  iot-broker:
    image: eclipse-mosquitto
    restart: always
    container_name: iot-broker
    volumes:
      - ./iot-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./iot-broker/data:/mosquitto/data
      - ./iot-broker/log:/mosquitto/log
    network_mode: 'host'
    ports:
      - 1883:1883
      - 9001:9001
  iot-sensors-raspberry:
    image: 'mtripsky/iot-sensors-raspberry:0.1.3'
    container_name: 'iot-sensors-raspberry'
    environment:
      - MQTT_BROKER_HOST=localhost
      - MQTT_BROKER_PORT=1883
      - NODE_ENV=production
    network_mode: 'host'
    privileged: true
    depends_on:
      iot-broker:
        condition: service_started
    devices:
      - /dev/gpiomem:dev/gpiomem
      - /dev/mem:/dev/mem
  iot-persistence:
    image: 'mtripsky/iot-persistence:0.1.3'
    container_name: 'iot-persistence'
    environment:
      - MQTT_BROKER_HOST=localhost
      - MQTT_BROKER_PORT=1883
      - NODE_ENV=production
      - FIREBASE_SERVICE_KEY='./serviceAccountKeyFirebase.json'
      - FIREBASE_URL='https://weather-station-etterbeek.firebaseio.com'
    network_mode: 'host'
    privileged: true
    depends_on:
      iot-broker:
        condition: service_started
    devices:
      - /dev/gpiomem:dev/gpiomem
      - /dev/mem:/dev/mem
