FROM arm32v7/node:12-alpine

EXPOSE 8181


# Create the work dir and set permissions as WORKDIR set the permissions as root
RUN mkdir /home/node/app/ && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

# set the context from now on to use the root user for installing dependencies
USER root

# When using alpine, you need to install build dependencies for some node module to be able to be built natively
RUN apk --no-cache --virtual build-dependencies add \
    make \
    g++ \
    && npm install \
    && apk del build-dependencies

# set the context from now on to use the node user, which is created in the base image
#USER node 

RUN npm cache clean --force --loglevel=error

# Copy app source
COPY --chown=node:node index.js .
COPY --chown=node:node lib ./lib/
#COPY --chown=node:node db-keys ./db-keys/
RUN mkdir /home/node/app/db-keys && chown -R node:node /home/node/app/db-keys

CMD [ "node", "index.js"]
